name: Update Reuters RSS

on:
  schedule:
    - cron: "*/15 * * * *"  # every 15 mins
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install beautifulsoup4 requests
      - name: Generate RSS
        run: python reuters_world_rss.py
      - name: Commit & push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add reuters_world.xml
          git commit -m "Update Reuters feed"
          git push
